### ISSUE TITLE
Postup and postdown command need multicommand support.

### ISSUE THREAD

**Issue by laoshancun** [DefGuard/gateway#133]
For example:
```
POST_UP = iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -o eth+ -j MASQUERADE
POST_DOWN = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -o eth+ -j MASQUERADE
```

**Comment by teon** [comment]
@laoshancun to close the issue, here is the copy of my comment from the PR:

The one command in pre/post up/down is by design - as defguard is built with highest security standards in mind.

If someone requires multiple commands to be executed, they can create a shell script which will define the acceptable and preferred shell to use and then execute all commands.

Why?

Each administrator has a preferred shell, and also in the script they can do other arrangements to control the environment.

Also what you have proposed - to launch the "sh" shell is not secured, as it's first sh shell from the path - that can be used for example to exploit the server on the gateway.
And for that reason, we require the administrator to create a script in which **the shell is defined by the admin as well as accepted by the admin (can be full path, from env - but the admin accepts what it is)**.

**Comment by laoshancun** [comment]
fine.
