### ISSUE TITLE
Gateway on OPNSense with MFA disconnects after random 2-10 minutes...

### ISSUE THREAD

**Issue by teon** [DefGuard/gateway#80]

**Comment by wojcik91** [comment]
In my case it seems the issue was incorrect configuration of our services. The client itself worked correctly.

Disconnecting peers is done based on interface stats collected from the gateway. In this situation relevant parameters looked as follows:
- stats period: 60s
- peer disconnect threshold: 180s
- peer disconnect task iteration: 60s
Since wireguard handshake happens around every 2 minutes (and sometimes more) it seems feasible that a client could be prematurely disconnected.
Before the next test I increased the disconnect threshold to 5 minutes and stats frequency to 30s.

**Comment by wojcik91** [comment]
- GW fix was implemented in https://github.com/DefGuard/wireguard-rs/pull/53
- settings were adjusted

What still needs to be done (probably as a separate task):
- debug & fix Windows client
- release new version of the gateway
- do another round of testing
